//Get all
GET http://localhost:5000/api/accessories/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmI0ZDhjZDgzYTcxMTBkMDU4OTljNiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYzOTY2NjA2MywiZXhwIjoxNjQxNzM5NjYzLCJpYXQiOjE2Mzk2NjYwNjN9.BlW-gxrz_NS730HSuS0dsIG6J5NpMgSZ_Z2HqbAHXzk

###
//Get 1

GET http://localhost:5000/api/accessories/60b6fef1462dd867ab0eaaa5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmI0ZDhjZDgzYTcxMTBkMDU4OTljNiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYzOTY2NjA2MywiZXhwIjoxNjQxNzM5NjYzLCJpYXQiOjE2Mzk2NjYwNjN9.BlW-gxrz_NS730HSuS0dsIG6J5NpMgSZ_Z2HqbAHXzk

