
//Get all
GET http://localhost:5000/api/accessory-receipts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTg5MDcwMjAxZDJkZDg0NWI0ZGNiYiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYyMjg3NjMwMywiZXhwIjoxNjI0OTQ5OTAzLCJpYXQiOjE2MjI4NzYzMDN9.mHKSKMO9cQkg2xQ20B9PUciqMqekijdtJRfjivWs3jE

###
//Get 1
GET http://localhost:5000/api/accessory-receipts/60c22c1dcf7311797efa9c07
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTg5MDcwMjAxZDJkZDg0NWI0ZGNiYiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYyMjg3NjMwMywiZXhwIjoxNjI0OTQ5OTAzLCJpYXQiOjE2MjI4NzYzMDN9.mHKSKMO9cQkg2xQ20B9PUciqMqekijdtJRfjivWs3jE


###
//create
POST http://localhost:5000/api/accessory-receipts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTg5MDcwMjAxZDJkZDg0NWI0ZGNiYiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYyNDQzNjg3MywiZXhwIjoxNjI2NTEwNDczLCJpYXQiOjE2MjQ0MzY4NzN9.2MkfFjkQjFLHHpFNGF6DDBuPJMCanlG-EtjgYLdQBwQ
Content-Type: application/json

[
    {
        "name": "Nhớt Ô tô",
        "quantity": 15,
        "unit": "Thùng",
        "receiptPrice": 4000000,
        "expiredTime": "2030-01-30T17:16:40",
        "providerId": "60bb97450325b6fff4b63067",
        "accessoryTypeId": "60c23193ea09602510dca3fd",
        "description": "Nhớt"
    },
    {
        "name": "Kính chiếu hậu ô tô",
        "quantity": 10,
        "unit": "Cái",
        "receiptPrice": 5000000,
        "expiredTime": "2025-02-28T00:00:00",
        "providerId": "60bb97450325b6fff4b63067", 
        "accessoryTypeId": "60bf9781a352eee743e6b3f0",  
        "description": "Ắc quy 250V, dùng cho xe 16 chỗ"  
    }
]