//Get annual Report
GET http://localhost:5000/api/report/accessory-receipt/?option=annual&year=2021
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmI4MWI4MjM0ZjIwZmFkN2E3MTdlNyIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYyMzk0NDY0MiwiZXhwIjoxNjI2MDE4MjQyLCJpYXQiOjE2MjM5NDQ2NDJ9.tWrmNJuX8UE1w3geCpTl26ArLd86x5vUbGykeE-1RtQ
###
//Get monthly report
GET http://localhost:5000/api/report/accessory-receipt/?option=monthly&year=2021&month=6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmI4MWI4MjM0ZjIwZmFkN2E3MTdlNyIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYyMzk0NDY0MiwiZXhwIjoxNjI2MDE4MjQyLCJpYXQiOjE2MjM5NDQ2NDJ9.tWrmNJuX8UE1w3geCpTl26ArLd86x5vUbGykeE-1RtQ