GET http://localhost:5000/api/accessory-issues/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTg5MDcwMjAxZDJkZDg0NWI0ZGNiYiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYyMjg3NjMwMywiZXhwIjoxNjI0OTQ5OTAzLCJpYXQiOjE2MjI4NzYzMDN9.mHKSKMO9cQkg2xQ20B9PUciqMqekijdtJRfjivWs3jE

###
POST http://localhost:5000/api/accessory-issues/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmI4MWI4MjM0ZjIwZmFkN2E3MTdlNyIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYyMzk0NDY0MiwiZXhwIjoxNjI2MDE4MjQyLCJpYXQiOjE2MjM5NDQ2NDJ9.tWrmNJuX8UE1w3geCpTl26ArLd86x5vUbGykeE-1RtQ
Content-Type: application/json

{
    "Receiver": "Nguyen van A",
    "RepairedRequestId": "60cf91106320e3a7165524d2"
}