//Get annual Report
GET http://localhost:5000/api/report/accessory-receipt/?option=annual&year=2021
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmI0ZDhjZDgzYTcxMTBkMDU4OTljNiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYzOTY2NjA2MywiZXhwIjoxNjQxNzM5NjYzLCJpYXQiOjE2Mzk2NjYwNjN9.BlW-gxrz_NS730HSuS0dsIG6J5NpMgSZ_Z2HqbAHXzk
###
//Get monthly report
GET http://localhost:5000/api/report/accessory-receipt/?option=monthly&year=2021&month=6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmI0ZDhjZDgzYTcxMTBkMDU4OTljNiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYzOTY2NjA2MywiZXhwIjoxNjQxNzM5NjYzLCJpYXQiOjE2Mzk2NjYwNjN9.BlW-gxrz_NS730HSuS0dsIG6J5NpMgSZ_Z2HqbAHXzk