// get all
GET http://localhost:5000/api/bills/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmI0ZDhjZDgzYTcxMTBkMDU4OTljNiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYzOTY2NjA2MywiZXhwIjoxNjQxNzM5NjYzLCJpYXQiOjE2Mzk2NjYwNjN9.BlW-gxrz_NS730HSuS0dsIG6J5NpMgSZ_Z2HqbAHXzk
###
POST http://localhost:5000/api/bills/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmI0ZDhjZDgzYTcxMTBkMDU4OTljNiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYzOTY2NjA2MywiZXhwIjoxNjQxNzM5NjYzLCJpYXQiOjE2Mzk2NjYwNjN9.BlW-gxrz_NS730HSuS0dsIG6J5NpMgSZ_Z2HqbAHXzk

{
    "discount": 0, 
    "vat": 0, 
    "RepairedRequestId": "60ccba963e00cb1ee680bef1", 
    "CustomerId": "60cc47f26b3367a7f24e9218"
}

###
GET http://localhost:5000/api/bills/60b6fef1462dd867ab0aaaa2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmI0ZDhjZDgzYTcxMTBkMDU4OTljNiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYzOTY2NjA2MywiZXhwIjoxNjQxNzM5NjYzLCJpYXQiOjE2Mzk2NjYwNjN9.BlW-gxrz_NS730HSuS0dsIG6J5NpMgSZ_Z2HqbAHXzk


###
//get all with accessory name
GET http://localhost:5000/api/bills/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmI0ZDhjZDgzYTcxMTBkMDU4OTljNiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYzOTY2NjA2MywiZXhwIjoxNjQxNzM5NjYzLCJpYXQiOjE2Mzk2NjYwNjN9.BlW-gxrz_NS730HSuS0dsIG6J5NpMgSZ_Z2HqbAHXzk