// get all
GET http://localhost:5000/api/cars/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmFlNTFhMWNiM2NmNjVhYjVhOGU5OCIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYyNDE4MTIyNCwiZXhwIjoxNjI2MjU0ODI0LCJpYXQiOjE2MjQxODEyMjR9.M2q9shpJ2LhThlo2c4Ylq6sNsYk_lIzQYjCuyUzMub8

### create 
POST http://localhost:5000/api/cars/
Content-Type: application/x-www-form-urlencoded

numberplate=75x-77777
&vin=1234221332322
&registerid=d123c12424124
&owner=Thieu Quang

// get by id
GET http://localhost:5000/api/cars/search?type=id&value=60bdfcf2bf67fb6dfa3850e2

// get by numberplate
GET http://localhost:5000/api/cars/search?type=numberplate&value=75x-77777

// get by vin
GET http://localhost:5000/api/cars/search?type=vin&value=1234221332322

// delete
DELETE http://localhost:5000/api/cars/60bdfcf2bf67fb6dfa3850e2

### update car
PUT http://localhost:5000/api/cars/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmFlNTFhMWNiM2NmNjVhYjVhOGU5OCIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYyNDE4MTIyNCwiZXhwIjoxNjI2MjU0ODI0LCJpYXQiOjE2MjQxODEyMjR9.M2q9shpJ2LhThlo2c4Ylq6sNsYk_lIzQYjCuyUzMub8
Content-Type: application/json

{
    "id": "60cc402f6b3367a7f24e9211",
    "owner": "Võ Thanh Bình",
}
