//GET all
GET http://localhost:5000/api/customers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmI0ZDhjZDgzYTcxMTBkMDU4OTljNiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYzOTY2NjA2MywiZXhwIjoxNjQxNzM5NjYzLCJpYXQiOjE2Mzk2NjYwNjN9.BlW-gxrz_NS730HSuS0dsIG6J5NpMgSZ_Z2HqbAHXzk


###

//Get 1 customer
GET http://localhost:5000/api/customers/60b6fef9462dd867ab07b4dc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmI0ZDhjZDgzYTcxMTBkMDU4OTljNiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYzOTY2NjA2MywiZXhwIjoxNjQxNzM5NjYzLCJpYXQiOjE2Mzk2NjYwNjN9.BlW-gxrz_NS730HSuS0dsIG6J5NpMgSZ_Z2HqbAHXzk


###

//create customer
POST http://localhost:5000/api/customers/
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmI0ZDhjZDgzYTcxMTBkMDU4OTljNiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYzOTY2NjA2MywiZXhwIjoxNjQxNzM5NjYzLCJpYXQiOjE2Mzk2NjYwNjN9.BlW-gxrz_NS730HSuS0dsIG6J5NpMgSZ_Z2HqbAHXzk

name=Trương Bá Cường
&address=Quảng Bình
&phoneNumber=049111838232
&email=cuong@gmail.com

###
//delete customer

DELETE  http://localhost:5000/api/customers/60befc1bbd639ffa5044ac18
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmI0ZDhjZDgzYTcxMTBkMDU4OTljNiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYzOTY2NjA2MywiZXhwIjoxNjQxNzM5NjYzLCJpYXQiOjE2Mzk2NjYwNjN9.BlW-gxrz_NS730HSuS0dsIG6J5NpMgSZ_Z2HqbAHXzk


###
//update customer

PUT http://localhost:5000/api/customers/60b6fef9462dd867ab07b4dc
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmI0ZDhjZDgzYTcxMTBkMDU4OTljNiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYzOTY2NjA2MywiZXhwIjoxNjQxNzM5NjYzLCJpYXQiOjE2Mzk2NjYwNjN9.BlW-gxrz_NS730HSuS0dsIG6J5NpMgSZ_Z2HqbAHXzk

name=Phan Quốc An
&address=Long An
&phoneNumber=0928118233
&email=AnOhmygod@gmail.com