//Get annual Report
GET http://localhost:5000/api/report/new-customer?option=annual&year=2021
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYWZhZTI3NTIxZmNmNDNjMTYwNTg2NiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYyNDExMjA0MSwiZXhwIjoxNjI2MTg1NjQxLCJpYXQiOjE2MjQxMTIwNDF9.uR4YOw8TWOOh3ZTFDgwc5BPd9pCtm01sWyMshiFHGqw

###
//Get monthly report
GET http://localhost:5000/api/report/new-customer?option=monthly&year=2021&month=6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYWZhZTI3NTIxZmNmNDNjMTYwNTg2NiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYyNDExMjA0MSwiZXhwIjoxNjI2MTg1NjQxLCJpYXQiOjE2MjQxMTIwNDF9.uR4YOw8TWOOh3ZTFDgwc5BPd9pCtm01sWyMshiFHGqw
