//Get annual Report
GET http://localhost:5000/api/report/revenue?option=annual&year=2021
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTg5MDcwMjAxZDJkZDg0NWI0ZGNiYiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYyMjg3NjMwMywiZXhwIjoxNjI0OTQ5OTAzLCJpYXQiOjE2MjI4NzYzMDN9.mHKSKMO9cQkg2xQ20B9PUciqMqekijdtJRfjivWs3jE

###
//Get monthly report
GET http://localhost:5000/api/report/revenue?option=monthly&year=2021&month=6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYWZhZTI3NTIxZmNmNDNjMTYwNTg2NiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYyNDExMjA0MSwiZXhwIjoxNjI2MTg1NjQxLCJpYXQiOjE2MjQxMTIwNDF9.uR4YOw8TWOOh3ZTFDgwc5BPd9pCtm01sWyMshiFHGqw
