//GET ALL ROLES
GET http://localhost:5000/api/users/roles/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmI0ZDhjZDgzYTcxMTBkMDU4OTljNiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYzOTY2NjA2MywiZXhwIjoxNjQxNzM5NjYzLCJpYXQiOjE2Mzk2NjYwNjN9.BlW-gxrz_NS730HSuS0dsIG6J5NpMgSZ_Z2HqbAHXzk

###
//GET ALL USERS
GET http://localhost:5000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmI0ZDhjZDgzYTcxMTBkMDU4OTljNiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYzOTY2NjA2MywiZXhwIjoxNjQxNzM5NjYzLCJpYXQiOjE2Mzk2NjYwNjN9.BlW-gxrz_NS730HSuS0dsIG6J5NpMgSZ_Z2HqbAHXzk

###
//GET 1 USER
GET http://localhost:5000/api/users/60b65754dc49e4c97a55c39b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmI0ZDhjZDgzYTcxMTBkMDU4OTljNiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYzOTY2NjA2MywiZXhwIjoxNjQxNzM5NjYzLCJpYXQiOjE2Mzk2NjYwNjN9.BlW-gxrz_NS730HSuS0dsIG6J5NpMgSZ_Z2HqbAHXzk

###
//CREATE USER
POST http://localhost:5000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmI0ZDhjZDgzYTcxMTBkMDU4OTljNiIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTYzOTY2NjA2MywiZXhwIjoxNjQxNzM5NjYzLCJpYXQiOjE2Mzk2NjYwNjN9.BlW-gxrz_NS730HSuS0dsIG6J5NpMgSZ_Z2HqbAHXzk
Content-Type: application/x-www-form-urlencoded

username=admin4
&password=admin
&roleid=60a8898b2f7d4ec5e6c3951d
&phoneNumber=0391932193
&email=admin@gmail.com
&fullname=Admin 2 dep trai
&dateOB=21-12-1999
&address=Việt Nam



