import { validateUser } from "./Employee.js";

test.each([
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "abcxyz",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    true,
  ],
  [
    {
      roleId: "",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "abcxyz",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh.com",
      password: "Binh123@",
      username: "abcxyz",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "",
      password: "Binh123@",
      username: "abcxyz",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "",
      username: "abcxyz",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "binh123@",
      username: "abcxyz",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "BINH123@",
      username: "abcxyz",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binhhhh@",
      username: "abcxyz",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh1233",
      username: "abcxyz",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "B123@",
      username: "abcxyz",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "user name",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: ".user",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "username.",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "_username",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "username_",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "user..name",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "user__name",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "user._name",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "user_.name",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "username@",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "abcxyz",
      phoneNumber: "",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "abcxyz",
      phoneNumber: "0123456789a",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "abcxyz",
      phoneNumber: "012345678",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "abcxyz",
      phoneNumber: "0123456789",
      address: "",
      fullName: "Vo Thanh Binh",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "abcxyz",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "abcxyz",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh 1",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "abcxyz",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh @",
      dateOB: "22/04/2000",
    },
    false,
  ],
  [
    {
      roleId: "abcxyz",
      email: "binh@gmail.com",
      password: "Binh123@",
      username: "abcxyz",
      phoneNumber: "0123456789",
      address: "abcxyz",
      fullName: "Vo Thanh Binh",
      dateOB: "",
    },
    false,
  ],
  [
    {
      roleId: "",
      email: "",
      password: "",
      username: "",
      phoneNumber: "",
      address: "",
      fullName: "",
      dateOB: "",
    },
    false,
  ],
])(
  "Should return [expected] when validateUser for [user] ",
  (user, expected) => {
    expect(validateUser(user)).toEqual(expected);
  }
);
